### ISSUE TITLE
Issue with effects

### ISSUE THREAD

**Issue by Freeze7x** [skymen/mask#2]
![image](https://github.com/skymen/mask/assets/92553892/fe222393-4e06-403c-b2dc-5440cfe1687b)

When certain effects or a combination of effects are applied to objects between the mask, they don't behave as they should. The only instance I found where one effect caused this was able to find was with betteroutline, while usually a duplicate of the same effect (AdjustHSL) causes it as well.

[example-clipping-mask.c3p](https://github.com/skymen/mask/files/14016805/example-clipping-mask.zip)

**Comment by skymen** [comment]
This should be fixed in 1.0.0.7

(Sorry, forgot to post an update here)
https://www.construct.net/en/make-games/addons/1183/clipping-mask/versions
